language: python

python:
  - "3.6"

branches:
  only:
    - master

env:
  global:
    - TWILIO_ACCOUNT_SID=my-account-sid
    - TWILIO_AUTH_TOKEN=my-auth-token
    - TWILIO_SENDING_NUMBER=+1234567891

cache: pip

install:
  - make install

script:
  - make format
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
